[api]
api_url="https://virtserver.swaggerhub.com/wcd_de_lab/top10/1.0.0/add"

[s3]
bucket='mini-project-amjadbq'
folder='input'

[db]
host='mini-project-database.c12usqgk8zwr.eu-north-1.rds.amazonaws.com'
port=3306
database='Project'
schema='superstore'




    

    